applications:
  App1:
    groupId: com.capgemini.tango
    increments:
    - {artifactId: inc1, name: Increment 1}
    - {artifactId: inc2, name: Increment 2}
    name: TANGO
  App2:
    groupId: com.capgemini.compass
    increments:
    - {artifactId: inc1, name: Increment 1}
    - {artifactId: inc2, name: Increment 2}
    name: COMPASS
  App3:
    groupId: com.capgemini.test
    increments:
    - {artifactId: inc1, name: Increment 1}
    - {artifactId: inc2, name: Increment 2}
    name: TESTAPP
  App4:
    groupId: com.capgemini.pt.selfservice
    increments:
    - {artifactId: inc1, name: Increment 1}
    - {artifactId: inc2, name: Increment 2}
    name: PT-SELF-SERVICE
  App5:
    groupId: org.hibernate
    increments:
    - {artifactId: hibernate-search-testing, name: Hibernate Search Testing}
    - {artifactId: hibernate-validator, name: Hibernate Validator}
    name: HIBERNATE
  App6:
    groupId: org.hibernate
    increments:
    - {artifactId: hibernate-search-testing, name: Hibernate Search Testing}
    - {artifactId: hibernate-validator, name: Hibernate Validator}
    name: TESTNEU
